# .sops.yaml
creation_rules:
  # Encrypt only Kubernetes Secret payloads written as *.sops.yaml files.
  - path_regex: '.*\.sops\.ya?ml$'
    encrypted_regex: '^(data|stringData)$'
    key_groups:
      - age:
          - "age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa"
