apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: andy
  name: demo1-andy
spec:
  answers:
    - questionId: stack
      singleChoice: Neither yet
    - questionId: packaging
      singleChoice: Plain YAML
    - multiChoice:
        - A web UI or portal
      questionId: approach
    - freeText: test
      questionId: wish
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:45:27Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: aim
  name: demo1-aim
spec:
  answers:
    - questionId: stack
      singleChoice: Argo CD
    - questionId: packaging
      singleChoice: Helm
    - multiChoice:
        - A pull request to a GitOps repo
      questionId: approach
    - freeText: Coffee
      questionId: wish
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:45:28Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: Billy-Butcher
  name: demo1-billy-butcher
spec:
  answers:
    - questionId: stack
      singleChoice: Argo CD
    - questionId: packaging
      singleChoice: Both
    - multiChoice:
        - A pull request to a GitOps repo
      questionId: approach
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:45:34Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: msutth
  name: demo1-msutth
spec:
  answers:
    - questionId: stack
      singleChoice: Argo CD
    - questionId: packaging
      singleChoice: Helm
    - multiChoice:
        - A pull request to a GitOps repo
        - kubectl apply
        - A web UI or portal
        - I ask someone in Slack or a ticket
        - Someone else does it entirely
      questionId: approach
    - freeText: "not responsive \U0001F62D\U0001F62D"
      questionId: wish
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:45:45Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: in0rdr
  name: demo1-in0rdr
spec:
  answers:
    - questionId: stack
      singleChoice: Argo CD
    - questionId: packaging
      singleChoice: Helm
    - multiChoice:
        - A pull request to a GitOps repo
      questionId: approach
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:45:45Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: Carsnet
  name: demo1-carsnet
spec:
  answers:
    - questionId: stack
      singleChoice: Argo CD
    - questionId: packaging
      singleChoice: Both
    - multiChoice:
        - A pull request to a GitOps repo
        - kubectl apply
        - A web UI or portal
        - I ask someone in Slack or a ticket
        - Someone else does it entirely
      questionId: approach
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:45:51Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: DefinitlyNo666
  name: demo1-definitlyno666
spec:
  answers:
    - questionId: stack
      singleChoice: Argo CD
    - questionId: packaging
      singleChoice: Helm
    - multiChoice:
        - A pull request to a GitOps repo
      questionId: approach
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:45:52Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: Thom
  name: demo1-thom
spec:
  answers:
    - questionId: stack
      singleChoice: Flux
    - questionId: packaging
      singleChoice: Plain YAML
    - multiChoice:
        - A pull request to a GitOps repo
      questionId: approach
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:45:56Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: DS
  name: demo1-ds
spec:
  answers:
    - questionId: stack
      singleChoice: Argo CD
    - questionId: packaging
      singleChoice: Both
    - multiChoice:
        - A pull request to a GitOps repo
        - A web UI or portal
      questionId: approach
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:46:02Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: Faaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab
  name: demo1-faaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab
spec:
  answers:
    - questionId: stack
      singleChoice: Flux
    - questionId: packaging
      singleChoice: Kustomize
    - multiChoice:
        - A pull request to a GitOps repo
      questionId: approach
    - freeText: cluster bootstraping
      questionId: wish
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:46:09Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: roompass
  name: demo1-roompass
spec:
  answers:
    - questionId: stack
      singleChoice: Argo CD
    - questionId: packaging
      singleChoice: Both
    - multiChoice:
        - A web UI or portal
      questionId: approach
    - freeText: Github Apps
      questionId: wish
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:46:09Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: marc
  name: demo1-marc
spec:
  answers:
    - questionId: stack
      singleChoice: Argo CD
    - questionId: packaging
      singleChoice: Helm
    - multiChoice:
        - A pull request to a GitOps repo
      questionId: approach
    - freeText: Databases and persistent storage.
      questionId: wish
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:46:14Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: drop-table-where-1-1
  name: demo1-drop-table-where-1-1
spec:
  answers:
    - questionId: stack
      singleChoice: Argo CD
    - questionId: packaging
      singleChoice: Plain YAML
    - multiChoice:
        - Someone else does it entirely
      questionId: approach
    - freeText: 'Everything. '
      questionId: wish
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:46:15Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: Ced
  name: demo1-ced
spec:
  answers:
    - questionId: stack
      singleChoice: Argo CD
    - questionId: packaging
      singleChoice: Both
    - multiChoice:
        - A pull request to a GitOps repo
      questionId: approach
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:46:21Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: Test2
  name: demo1-test2
spec:
  answers:
    - questionId: stack
      singleChoice: Argo CD
    - questionId: packaging
      singleChoice: Both
    - multiChoice:
        - A web UI or portal
        - kubectl apply
        - A pull request to a GitOps repo
      questionId: approach
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:46:21Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: Luca
  name: demo1-luca
spec:
  answers:
    - questionId: stack
      singleChoice: Argo CD
    - questionId: packaging
      singleChoice: Helm
    - multiChoice:
        - kubectl apply
        - Someone else does it entirely
        - I ask someone in Slack or a ticket
      questionId: approach
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:46:21Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: stabibi
  name: demo1-stabibi
spec:
  answers:
    - questionId: stack
      singleChoice: Argo CD
    - questionId: packaging
      singleChoice: Both
    - multiChoice:
        - A pull request to a GitOps repo
      questionId: approach
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:46:25Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: m
  name: demo1-m
spec:
  answers:
    - questionId: stack
      singleChoice: Argo CD
    - questionId: packaging
      singleChoice: Helm
    - multiChoice:
        - A pull request to a GitOps repo
      questionId: approach
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:46:29Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: Diego
  name: demo1-diego
spec:
  answers:
    - questionId: stack
      singleChoice: Argo CD
    - questionId: packaging
      singleChoice: Both
    - multiChoice:
        - A pull request to a GitOps repo
        - kubectl apply
      questionId: approach
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:46:32Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: luca-hom
  name: demo1-luca-hom
spec:
  answers:
    - questionId: stack
      singleChoice: Flux
    - questionId: packaging
      singleChoice: Helm
    - multiChoice:
        - A pull request to a GitOps repo
      questionId: approach
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:46:33Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: Pascal
  name: demo1-pascal
spec:
  answers:
    - questionId: stack
      singleChoice: Argo CD
    - questionId: packaging
      singleChoice: Kustomize
    - multiChoice:
        - A pull request to a GitOps repo
      questionId: approach
    - freeText: Everything
      questionId: wish
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:46:36Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: HuJa
  name: demo1-huja
spec:
  answers:
    - questionId: stack
      singleChoice: Argo CD
    - questionId: packaging
      singleChoice: Plain YAML
    - multiChoice:
        - A pull request to a GitOps repo
        - I ask someone in Slack or a ticket
      questionId: approach
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:46:40Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: Verstappen
  name: demo1-verstappen
spec:
  answers:
    - questionId: stack
      singleChoice: Argo CD
    - questionId: packaging
      singleChoice: Plain YAML
    - multiChoice:
        - A pull request to a GitOps repo
      questionId: approach
    - freeText: New C-Level
      questionId: wish
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:46:45Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: isurri
  name: demo1-isurri
spec:
  answers:
    - questionId: stack
      singleChoice: Argo CD
    - questionId: packaging
      singleChoice: Helm
    - multiChoice:
        - A pull request to a GitOps repo
      questionId: approach
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:46:45Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: Robin
  name: demo1-robin
spec:
  answers:
    - questionId: stack
      singleChoice: Flux
    - questionId: packaging
      singleChoice: Both
    - multiChoice:
        - A pull request to a GitOps repo
      questionId: approach
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:46:49Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: hello
  name: demo1-hello
spec:
  answers:
    - questionId: stack
      singleChoice: Flux
    - questionId: packaging
      singleChoice: Both
    - multiChoice:
        - A pull request to a GitOps repo
      questionId: approach
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:46:52Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: Raphael
  name: demo1-raphael
spec:
  answers:
    - questionId: stack
      singleChoice: Neither yet
    - questionId: packaging
      singleChoice: Helm
    - multiChoice:
        - A pull request to a GitOps repo
      questionId: approach
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:46:58Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: Markus
  name: demo1-markus
spec:
  answers:
    - questionId: stack
      singleChoice: Argo CD
    - questionId: packaging
      singleChoice: Both
    - multiChoice:
        - A pull request to a GitOps repo
      questionId: approach
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:47:10Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: Alex
  name: demo1-alex
spec:
  answers:
    - questionId: stack
      singleChoice: Argo CD
    - questionId: packaging
      singleChoice: Both
    - multiChoice:
        - A pull request to a GitOps repo
        - kubectl apply
      questionId: approach
    - freeText: 'Happiness '
      questionId: wish
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:47:15Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: h4x0r
  name: demo1-h4x0r
spec:
  answers:
    - questionId: stack
      singleChoice: Argo CD
    - questionId: packaging
      singleChoice: Helm
    - multiChoice:
        - A pull request to a GitOps repo
      questionId: approach
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:47:15Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: LTXKRS
  name: demo1-ltxkrs
spec:
  answers:
    - questionId: stack
      singleChoice: Both
    - questionId: packaging
      singleChoice: Helm
    - multiChoice:
        - kubectl apply
        - A web UI or portal
      questionId: approach
    - freeText: Everything
      questionId: wish
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:47:20Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: cthulu
  name: demo1-cthulu
spec:
  answers:
    - questionId: stack
      singleChoice: Argo CD
    - questionId: packaging
      singleChoice: Helm
    - multiChoice:
        - A pull request to a GitOps repo
      questionId: approach
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:47:21Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: Helloworld
  name: demo1-helloworld
spec:
  answers:
    - questionId: stack
      singleChoice: Both
    - questionId: packaging
      singleChoice: Both
    - multiChoice:
        - A pull request to a GitOps repo
      questionId: approach
    - freeText: Test
      questionId: wish
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:47:26Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: demo1
    voter.configbutler.ai/submitter: scn
  name: demo1-scn
spec:
  answers:
    - questionId: stack
      singleChoice: Neither yet
    - questionId: packaging
      singleChoice: Both
    - multiChoice:
        - kubectl apply
      questionId: approach
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: demo1
  submittedAt: "2026-09-17T09:47:29Z"
