apiVersion: examples.configbutler.ai/v1alpha1
kind: CoffeeConfig
metadata:
  name: demo-coffee
spec:
  bannerText: "There is no spoonooooo"
  currency: CHF
  mail:
    apiKeySecretRef: {}
  payments:
    apiKeySecretRef: {}
    zeroAmountCheckoutAllowed: true
  products: []
  shopName: "☕"
  vouchers: []
