apiVersion: v1
kind: Secret
metadata:
    annotations:
        configbutler.ai/age-recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
        configbutler.ai/backup-warning: REMOVE_AFTER_BACKUP
    name: gitops-reverser-age
    namespace: voter
data:
    20260915.agekey: ENC[AES256_GCM,data:AYcWwC9OErT0LLYe6WjsAGkL1kY776uQiDtBp/1uu/xmHTjamHQtcWdsWcir/+AxY4fPnW+Tb2u+/4MFQhLU3pflBgBqOK/qiByrASpRhFsubazXOopsR293OFqoPZjqFSfdyQ==,iv:R9bejDtfNFj7UGQreGlr3atNxXmVdIs2oI7ugJIKmhI=,tag:Irif4gNX5gbKQzwX4Eqv1Q==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WnhOVkZ0L3B5YnNBb3JG
            S3lSR1dkc01mTGo5MUFBYnEybUhjWk8xOUdZCnJSbm1tK2lIZjVXcTJMSWhCdER0
            aG9MTGZTY0QveXlyclpud3VRTFMxMTgKLS0tIEc2c01jVVgrWnJuS2pmczc0b0Q5
            QUY3NWtEVU00WDhyejRrVTFsL2ZQMG8KQAw6BLB7rcJpWEXHWEgW95r8Ax7IlnSL
            FkqDzczg5l/EJZbbKWCNG21qU8INrMfN5jwWAG88Jw1NUMo7ddrOvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T13:25:56Z"
    mac: ENC[AES256_GCM,data:WtQwMfbc7+nTXE216JQMaYE47Py+lDECRv89MMOV0ekTOFLR09GPbVMCe3VmEVgwyOK1ypzEiUTxYMAjDHSdQF5bkIA33xgu/EvnFiQu8WXDtJlvBvPoJMrO3Q4Ge2OCDgLbSPqjhQjtVPP5d8KthLHmKliAhDrgi5t7/lLoUoY=,iv:AfFeu3Rg/nXTrZ3leqt/AAWFyedjPRDMkX0cNbCgeKs=,tag:W1oV9JECA/LVTT1O6YrR7g==,type:str]
    version: 3.13.3
