apiVersion: v1
kind: Secret
metadata:
    annotations:
        configbutler.ai/age-recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
        configbutler.ai/backup-warning: REMOVE_AFTER_BACKUP
    name: gitops-reverser-age
    namespace: voter
data:
    20260915.agekey: ENC[AES256_GCM,data:3Mtk3RNc6PwRQIqwHigscoNIiXLNqK/iKmMHZf6ytX2Ixnbgh6y3uucAybprbmnKk7ud3NnB4KpkOw7mCqIqpGFD35MH0X8qG7YQvMknxEL9yE1m41jWyg8EWj+DJMJWmD9sPg==,iv:pQLbuLCJ16eHKNfMEP/VwuetMSmn5AeJrC+S/b31cO4=,tag:cTGQugwSrIgH88Hl8BP+fQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NDNaZWJRdUtUMGl5MEUr
            Sm50UXFjTnd4bmUvSGZrMDlmbXRQbE5nVFJZCkFPQzZoUHV0NkREYUtWeEpac3Rv
            RHJuQ25WdEJDUUFCdlEwUmhSVVpmbzgKLS0tIGV2dVRJM0FpcmhuS0w1L2Njb1g4
            Z0c5THV2QmRQK2JBbktjOTZTMnRiWmMK7HyLY7dHHpPeV4MC3ZpQhAs988s9Frnx
            K9hnsSR5TVxegj92tZX1XwIHdfqJukjKbWeF2cLB1gKOlBD66ntqVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T07:58:12Z"
    mac: ENC[AES256_GCM,data:IP/GcIEQoKxFHTzlq7o2LyQMH7lNzgVZd5cavk8m9YDPSmpkZxus5Gs0w8P56lu3orkobKyu+GWGec6EFWMynJoBsalw/3ON0psVNrom6WFXShyFQkybo67wUZ1xhHwZpwIZtPW02x7DIn82PFd3K2kkx//f/HlPWME2ty81U6o=,iv:PHAMHkK8sHeJV0XeGHoFKEwgG79Ma1n++HBJo59nVT4=,tag:HFe+GyzfCG6oNnrWbhUQ8w==,type:str]
    version: 3.13.3
