apiVersion: v1
kind: Secret
metadata:
    annotations:
        configbutler.ai/age-recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
        configbutler.ai/backup-warning: REMOVE_AFTER_BACKUP
    name: gitops-reverser-age
    namespace: voter
data:
    20260915.agekey: ENC[AES256_GCM,data:Fzz7odFxNBpQESyjlL4C3g4QDWOVobK79AcZMYBQwr5yxJjI6Cf3/MnvRWA+WbqgeAyXTnhf7QiDvVcCPvRQiYtxciBlqGquNwIOEFnx4QvFNirSf/HmZcwvIl9febbTQANmgw==,iv:5NcBbIySv+JITrL5mOZ0VAKK8LZBvcJkeOVQpLHnVUc=,tag:+ozwXLJlP9qJp7N9sX1G7A==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlME1idm8wekk1dDZUMitj
            OTBXbnBTUDZ2L3ZsMTFWL0QrckxjdmNBNndJClhlaDNpWHZ5cDlZa0dTM0JnUnYv
            TzVLL3dBa1o1b1o2UWYxWjVwSk0zczQKLS0tIHZZamVsV0F2RFpNcnJPL1daOVpL
            V1A0QkY4eEl0cE9wOXdQa2tEYnRMRFUKBs0vgRcTTM5DH1rSKG4V89+d0t9Fmvus
            bAhFpEuOSZPCl/fmIoDG6KLJqtet5gYTtXsEbLqHwKRBBQ/LcGCubg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T21:42:20Z"
    mac: ENC[AES256_GCM,data:NdW8yH6Wqnm6vRXc1Kt/KUX8iVjORicotg/jSIRck4AfJQEzs5EEzDYIfdcxmASfrMT1Eg2rVhU1Tp+5bjt8exvaeg16SffnowvS0bMjdxgN+5i8IXWrTgUVB9yUvE3EK3B+et1Tzmcp4CxYUQsrQhoFYdA2kPPhFClCgwcd3jA=,iv:eacW3Let1JNAj/8NmbIm89lJVIG300wW3T4w+W66x9g=,tag:ztlKbnvCHxlvVDcl5ALliw==,type:str]
    version: 3.13.3
