apiVersion: v1
kind: Secret
metadata:
    name: k8s-audit-trail-signing
    namespace: voter
data:
    signing.key: ENC[AES256_GCM,data:ohTKm9fCsrpj1fJH25Svv+5hUnfN+WGwpiD577eAojUtMIVQPHYaZyT+/R6gV8K9wQg2XfxxD3jLso9YXZ/visNadU9GSttbHdjuh554GNPKAPeb0pivq++ilMoqVyGa+9ejFWboTRSh6nCJfjGYGCiWjyC19VpbXACiMrON5obVelsU0hwZrhmE0lsY6drqDY2s3mHUIwlCKSpM7c4zjeAs/sPB78khLhQLqqJj/EEmnFG0yBtKP7W8WnfQ5WKhyZ9dbeEckV1klRWpuDBEIWpjNhxAhGbHdH3qRXIUecO3Ci2MFu3gYj5czqiwp1oG6jWUv8Y19r32hUAmTlKxxICwSCuAdQvzOzH12mHuc7XA+mqkU40NY9S1PSUTDv5eNmAEeCCYfs8Kk56OMurfnhdKgb8a9WHKMwPfG7hDik45FQh5tk4TOaMpSvDwcOp9db9bHTmVjDHOFcE6wcw23HEthAvUHq9m2zEiu3sv1n0lttzL3W1987rC9cDnndbgtmhgcoeB8jyQYmt8iJPJi+WTcKdJcpq+PHPG4nKatfwYMxF9wz4wed5Ov9zYl1PLF2uulO9ppUlZ7Gknp1Ao1rywlurUnjJRNq/ChaxwuK4ZOR3u9fWyHZORHWXKPbddwECyBfM51n+qb1jwxyFd6f055BZ2CqOC1RlXVis6re52SvEtta1/I3lOa00MglyYzr4ReUX8RYGgPn+uXS42Sx14jXY=,iv:cdlihk3mGkkigQYgTxfbEPvTavCdgrbQukxnpj42b2U=,tag:J3C39op9nDR4kep0gPZy5g==,type:str]
    signing.pub: ENC[AES256_GCM,data:jls8JA7+uzik/dXIxZ2dSZaD6caCJHbBkKmEYvP0KyDwjOdvo0OX0AypLLNyE3CB49fCusMSuWTV8RrkqHZ05c5jkHfSino3aV5QLFy3k+cDwWHBZRgCoQ5efqIzHUSt/7yrw94LJU+9bE2Cgub26B+2xiSjYWgmA2XoFa8+1/EgL+hlzb7lBA==,iv:XkHm7rhf2f80oETzg8d+eujqJQssxxHs0MAaer4zNvo=,tag:DjOheRpk+1eGieCHw3txYA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcUNBR2laZHkreUZRVkxz
            anl5aUJUaEoyZFI2N0dmbW5tWU4xWktnOFEwCndXZnhQMTVXVVhLWXFFMEtDL2VP
            WWhUbVhxS2FzSnRvem1FQ2hUQjZzTTQKLS0tIHI3Q1pqb3dra2hmOXR6aFBBRmNu
            MTFHaU01cy91N1pGcy9pcjFicW1OQm8KtCcKFZjCLp5g/ohfde+SHfDq/MTA+AOB
            t4WXdhf11pF7VLS+h46SR4oOFIFKrDcnXXGqkmLTA4mzrJvNSxWAsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T21:42:20Z"
    mac: ENC[AES256_GCM,data:t87PZ7EKEoyuIiC0itBpy8KCEYf7b3+NeBC2Pon6YEKclaSsFhNyKIofymgVYLVwiz1wm+9ou6RO4WffnVXZzwsuef5+90TT8VOmtIvXGb9U9Nfka8MSB6RMJiiYSMLIeVNX1ilafHvgTHzdWVb83UTd3a2i2ZXwe4y8GZ7rzv4=,iv:zoxB1q+UxPv+s9KfH490YSzKL1CymdAaP8eB/NJo3bg=,tag:RjqGRxFD8D9UdNCjOYT1Cg==,type:str]
    version: 3.13.3
