apiVersion: v1
kind: Secret
metadata:
    name: k8s-audit-trail-signing
    namespace: voter
data:
    signing.key: ENC[AES256_GCM,data:haNeWxuCX0fYFz/Gm0fDufLhSsNRjTycZlB5MzjIsf/T86LNpU9MazozVtZaqQWB5D6zaUsyuW3d+93L9S6qFTnHnmJkG9UM61nWNGSArGPXzPZm99YD9ifbwkAmTwLZz+jxWcJXOvOUdkO2kWRxSvSeFvVNra8+eLK7mnloKaGOPAm0M/cvZK5nlSkOUDC5zgMd5US0683UunJi80FnkR6d3th13RYXUXBU6YEp57v4+tZGEp3qaUDqirkhkSUaiKa42m9dsoN5oGMzMm0IJrOmUP+xkrPN/Bip6eowgO1DqpOPJTckhZ83UPrHLBrm4/Te83hryyVuVgLBrio37EwlshPtler55/gnzkVbGHpTGtlbGpfqtVlrvg0NouZzDrbIvdhtIghmd4Q2L+V4hvxQIM29Ss0t4GmnVLm9mGj4Tj//i9PTeXrD1UNMhcmb56sA5+ErpDxe8MqsH3AQUiSYCkgmUljte6eZFtml79v1ZqT6YJqVOJ3DG2OE3hJIjxwhMs/dT44t5MaeGI0fJOG1jxGVm2MPD9Mv+ffAocDJku+LMuud2YrwgBbCJoVUaonTac5JuQuhFqz6EL7PXytyPIr0D2H/5iErqdHdIadi1qM1OJDMpXpkmA/MkVlWIhEzS/XkFhUE9gCDRuZKw7ytkdn6fy6g+N4I8OdvuNlLUBg4rj50MXpQIxmAFP2Q43WUc3plB4VJVRwU2YEpYLgOpdk=,iv:FtKoZdrEfcQG2akVqJjd/U/iUUntkba/Fo1wkPdWhh8=,tag:zQBnyngurPOIdAMNZhKq4w==,type:str]
    signing.pub: ENC[AES256_GCM,data:83Ci2xtLYz5MmipCezkMXwiCoZPCIpBMAxNE7agg0bK2HfmtmPU/hVSpMgMTDsKweGWstCM97qpcztJTFMS7r2zfLQFeT/fgzddLMqo79DTKbI9NZHuXTgMPgitqC4M3GmhyGts0Ps4nKqPbgP0MySOfrbNArgA+Qp6UcGC+pd1rxqhsSANTng==,iv:Zx8dVeeAft0KTzARJm8d5S7T/UZV9Bkyl2CP8kLo5xQ=,tag:qx8BsNzfK30Zpq7IQ34HXA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTlp0RWdDK2swV3hVdml4
            WkJSM1hrQTU2ZnFTOGNKL2h2Z2E1cGRWVjNJCnBiSmVFOFJGQXRkRWtYdThjUzE3
            a2JIckxVc3l3ek5PTFVSVjlzTVpNdFUKLS0tIDJ4MjFacE83VytoTWpyTlFOcHNj
            UHgycXlXWC9HcERjUVU2KzhoWHNJZ1kK4wMzhfUpTSylavoWYd4neXsBlEBISk81
            iFHUFbROcgYOMkggk3dc3QmgT49wyl/PBMgD2SR+RnyXbVYIMOk3uQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T07:58:12Z"
    mac: ENC[AES256_GCM,data:91wh69W8qN8/fDKuQt1Sd1ix/7uqoiG+tdpS7IU7JE7r9i3c7bf0sqzxihLtcCyqMHKGO8mPdSsX3PhjMwCXUTLhDChhHC2bEzLk5BeFrXvnzJg1s8JAKlSBgn1ZGpCV12XMdH6qJtpe6ToeoBcwoVq+HOjyveLyQn/wVmgAIIU=,iv:rad8v+tF2clFWx5+M6DNGEJjPMKIb+N4Q8jXVCfILy4=,tag:cYp8N+6oIRERZ+g7ivES/A==,type:str]
    version: 3.13.3
