apiVersion: v1
kind: Secret
metadata:
    name: k8s-audit-trail-signing
    namespace: voter
data:
    signing.key: ENC[AES256_GCM,data:u0L+g42IGl8c+2wTTYyYv2F14A0ENv2zCL7yfL7ymKFih3vgu1A1gq0JqARHkgvDUd7jHiH/j4zfrdC7MUgkxjGB9DHJJAqkQ/f5PS6KFVAvpe5T0mgsrpuRA7nlkTzQZW/GgHYDVHvLZgmGQ0czFBtVNbr2Y/ZXnJ9+71vFnTnFmXiQMrKE06s7M4D99624JoguHjuYBigV2+E0YaTsmamqOOjfJwVwX7p5iYXcxJ6xWjCmCqh+Cyzc5BCmaCFG90Ymd/OY9XabvBHQerfgRZXYpAIBWGscYxOZuHR9I10j89jbvF2tOY/yfcFna9aBIAtfkjG9vxSsVVxYv+5i5LeBiJTyrMrCkDQPQJ86yYwZzA6KzPR6WrGHnCkF03ZdmATNRAyVDCF7wQAVaT6jWtmapat4GyH4HV7NoomfKJkHsm4fjlC0PaPNOy1UFz9BMkkZYFV+76/ZjCswRvMtup9CMo7sJpxEmhwXdbx0yXK7ehVQ7viLFWQzfsG3mGbqwkvQMOfp4/XMHFqEd2Iben2DA8+xdDic+IZfsMlKMZUjyTaoL8EhK9+TvC3mmNtUjk2F8l4YB7lox/Rnlsnk+uc2C9UI51P9x3tKgbvMydZ+rLEd8s+BLFLgQ1JLqRtzzGczXdZIYJyK3dYYnPhosHP/7UE/Kc4ZMs+X6wHYbzyYgyr40eIHXj25BXowYij5u2M/V5CprXOecCBpr2cXwWgE+nw=,iv:Bbn7i/LlFXlNGCj9leNbwRDbCMRHTScNukT6x4la3eY=,tag:23b9obtBHu/WMuxcROOO4g==,type:str]
    signing.pub: ENC[AES256_GCM,data:nVWo5KiJJVCInq/Mj4vdukL4Q185q6DoN1CGIu3dJHDtJoJX0Ceym3XJxEtKXYj+lKVg/Zxm768C1wqFt3lUdoziA0RQmk6mjSXQveiyA+OJSdraeH3HxlL8vZ4/DtS4s6HPgQza2h+fSe2qkpGP+apUIg1b1icDhoYDG3l7HziSfQja9GOnnQ==,iv:RwgLyQr0r2WEDIbBKWQiMuQUjSd0cuG3qvL9D28ny9c=,tag:FXmTEByCNgDRVRbEwYwf8w==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCY3VWZlE1UFNvNXF3Z1E2
            Ync3ZDFheHpNMUg4YldxaFd6ZUM2NTRZRkhnClkyZnhzS2JtNzdKNEhwczd3UzN3
            ZnB1R25NREMyQTB4NGg5Qk11YlRZSVUKLS0tIDZRc0NMbTZ6aXF5UXp3M1ZWbGdT
            cHh0NTJmUDExMEVoRFQrUlpHWWRuczgKErQImHPuMqbF5psuvP2/WUgRWU2F7heI
            fXJOLSowYdhzqFo8Iqlp4kNlpS/rTp22eoG5gphSQbJ59ZMI9852Pg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T02:45:02Z"
    mac: ENC[AES256_GCM,data:BsRykBYWtErC/mujlqgrCztRE0dyI9OEIsrn7OFHu6p8d0OC7xkBe2QYXFcdCJtMvAKinJztUiBGXW1MBpzde3EU6nZvpb4ehTSWTSZAX5kRWyZL52DGMt8KAYShXFMWr1V7zOj2GwVExFTK1vcR+gyy3eQeTxm1sfyAcrk7kTg=,iv:7GnwjeJyO1xJ1hHWPIVJO7CFz/vH7r7UQ3hYRv0sGYo=,tag:Uz2dWbhXc+mibq0XVBFqWg==,type:str]
    version: 3.13.3
