apiVersion: v1
kind: Secret
metadata:
    name: room-pass-cookie
    namespace: voter
data:
    block-key: ENC[AES256_GCM,data:4Ur9L1PY9y07T5bTr7hB1ngIxnrKlqaacK5DkQNYYGa21Sf3ZrNm1ZDlgG4=,iv:8DWYhXYJZ29EpOWl38HLXzbRWreegCP7JhoMb288ufY=,tag:foy2uA6GsGABc6U86CbZhw==,type:str]
    hash-key: ENC[AES256_GCM,data:57iUjjYGspOWil4k3Uzr/PIW90jNXzd24IwTMuFwafaGEEbeSeJhmOW2lAY=,iv:d7fRwzJIIhnssAwY8nmbGr3dAutwJ6NAn4gIRDaMxc0=,tag:iNfRT7ruWjEXy0D+FynW/w==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTXV6S3J1VEtQZnRkcENL
            dUhxZGtkRDhKWUcycDdIMUJWeEcvNUwzSmpvClc2TmhVOHJPN25HK1p4WHJCcjQ2
            cTg4RTlMVHdMdHdxTGJlRnJ5emQ0T0UKLS0tIGVmTUZ0eTFobFk4bFF0dE1rTDZl
            ci9WVzhqVTNTa3IyMlBLdFF0Q211ZVkKJfmM5PCYR+ivpgIGJde5x+g2kcLI9FAR
            jjuwGyEaf0PB2jUZfOVINEbx9Pz8r6+nbwKUh8AdMy5Xev/P2dGoBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T02:45:02Z"
    mac: ENC[AES256_GCM,data:uLz2ebnyhmSJlDgras64HWunaTGBHfINVSFncIErwsw3wdKRQdbFp2cIQn/XTlJdBcTbsrlXdb3sauxdO8so9iiVC+Rm/cePJnOD8Iek8plGhwXMjemA9HYXbHvMKosntz7BtSs5iZyq5FzaSpcji0OG8GC9x8K0H/DrSMmZP00=,iv:fQlofDNmyNYWXYoTjASqRNmuXfdDunioWO6PJkUkHuY=,tag:T5/0os8oGS5eDvkxLaSd/g==,type:str]
    version: 3.13.3
