apiVersion: v1
kind: Secret
metadata:
    name: room-pass-cookie
    namespace: voter
data:
    block-key: ENC[AES256_GCM,data:6vQSp/lD9eLx1tnI46DGXtNro4QQyNqadFuM9G0OypMIFb8MsWhqpCyAkfA=,iv:XV+qtv3sX2ePMnh6u3PdMbkAlFkaY3VrcU73o5V515k=,tag:vvy+NmL3d2FQds1sEkXyPw==,type:str]
    hash-key: ENC[AES256_GCM,data:DRP3OTSq+fC3/eZhIwgVH0HFFfRJ6+ZCbDbJpiZM+zMOe2ANQT2CRdE8Gyw=,iv:a/w1CBjNhC5JMW0zUoyKY7oSXNQu+Gel2jALTB4SxPo=,tag:qe7RxJV1gqr6nHZXdIK1Mw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMzZwQmk2Z2xvZHFrWUlY
            bzYvR3lVS3AwWFpxWVRPM0JDenBQTlRjaVY4CkQ5QUN1R3JtdjNUMHhsRW81d1Zt
            MHNheWdhUElpVExTeGJiOVM1NHAyZHcKLS0tIFA4SHBrVTMxelZwK1pWV3Qya0V2
            NFFkV1ViczlyWDZOUXlPdmJlN0hNb2MK2SYMxcpCFD3q28hicBCNDkzGROu0vKb5
            wo1AInb6jwyVLkpv2WKiX8Ol5Kn2IqZeYxEk0W0GSvSUnEcBGBwaVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T07:58:12Z"
    mac: ENC[AES256_GCM,data:ubAVHn52dw/1YHk24WwOCO4jxSyoPRH/1LFR9GJ/HinGlyCDS55J9xRR3dmzJka7JmIVfD4GiRm/Oge8yl8+I1HB/wZ9FICRF3dZDqlfA7y9z/CwtELVPoX/ETAhSt1YaeBb/FgPHT3Lmm1yndpQ0siF+UnKtG7ru0IhSq1kAHA=,iv:6Csa983hDWI0M9FuC8JWOUzpFItDbDhsCJE53loBJsc=,tag:a3CcHuSptGO5P+y50cFsxg==,type:str]
    version: 3.13.3
