apiVersion: v1
kind: Secret
metadata:
    name: room-pass-cookie
    namespace: voter
data:
    block-key: ENC[AES256_GCM,data:K4tTkwMHyVdzjJB0ISkU4XQcpxZ4su9aQpab786utRBZwy/++IbynfOKZTQ=,iv:QIi7J9Gj+Y8HNZDE5z8wm6AKeV+Ver4PQiB8pL/ImM8=,tag:tX2XkD/cpZaU5wuEKUTZkA==,type:str]
    hash-key: ENC[AES256_GCM,data:uRiSzrAbo8dhRq/XThsRSvP66t83A+HUnw2LvTOsoeGFuI1J1pNluO9IZME=,iv:gAu68qVPpwwlAiZDmed4qAcb2o/zD69BxtZylynoGvk=,tag:B7gaOHd7nOT8PwIcZcDQtA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcHZNU2g0NGJ2a0xiN2Iy
            M1hyMnczamhDMEFoc1A4RFFOWGhPYktzazE0CjVObkh5MFZsdFhUYUl1aTVtSUI5
            cWtiT1pUQzgrZnNqU3dXQnpqbkVEd1kKLS0tIFNjQnNSbVFkRFFHdTgzRk5naDlH
            N0NRY2RXVjd2cGJpcEtrUkpCdnVzOTgKGORgmZH9CNRxdBtBR9EdB/3lZKpcJgja
            +fsKyHGofylNdoAS5msv2BlLnCJUgtP6/gzUPE7/+YlfPessXm2FaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T21:42:20Z"
    mac: ENC[AES256_GCM,data:64SGP6hombxcaOSMjGv913iUsCQSB68na0yBcQ+RkAWZTukfw9ha1glyFkzNTlZIhy5bpeFZ6O0UtezMu6oWlc1eJS9P3Fo2p5uDHB7o5yykPOemkxgvHL5DKWsgKVOobphw2ECp86KcUOIbeTwBql8XIksMaqzBwVI+cuSKXbY=,iv:NKfcWmspywby4kZAQBswWlJU86nUtqrr0DmFoywIECw=,tag:DAlGOSXiqt6iBKnhNuRtGw==,type:str]
    version: 3.13.3
