apiVersion: v1
kind: Secret
metadata:
    name: voter-oidc-client
    namespace: voter
data:
    VOTER_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:XMXh+27aLrEN88KgWPjZ+r0y9P/H/preEQbQ4R4/lRsepQgBzdkqCvS/zlRrBXIezacJHOMUH2OTC0J1,iv:ydtG66hUqBDlMOIrCvDjPverYM8+ivvOWxT2/B90i/w=,tag:nC0P+cSMoIH+AP96xLAGiw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFR3VxU3FmU21aNVVVWW0w
            b3BqSjh6R2IwbnFIclVpcm1MT3EwNXFvQUdVCkU3cVNqY3pubHpYdE95U2ZIb3JW
            TzB5L3RKcHB6VGhBQVdXMXZ6cWVOeHcKLS0tIFNaSU1tTlE1WTJMclVWY2h2Tytl
            ekh0WFhFZVZteXVtaFJHUXVyVU5MN28KGWAiprBslW8VWCLGOBBi4UtAey8ICSa4
            /JURe6VSprDe4H7zccL7y1Ky4HeXNchC0bQ89+80b741mH3cuqSSbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T07:58:12Z"
    mac: ENC[AES256_GCM,data:+2pDMg446OrUuiGngeUP7BjV5+TeOmX4nfJuDcgixZhu9BNGtRXEldxwUC8lXMye/OBIegEyN6lnjN3b9qURpueV/+3wEAs7IYHyOrZnAaAu3mkJAPVz3Hdp6CbjVNtIj9kkf30m9PrtyjwPPKS2+r6o+hU8I/wo+uvoBY5jnf4=,iv:I6UR/++R1vYn5wl5+B8lsOqSUfdC2OzLlTBYV0qLGD0=,tag:uEuWejVPgCvhwd7h0i3qcg==,type:str]
    version: 3.13.3
