apiVersion: v1
kind: Secret
metadata:
    name: voter-oidc-client
    namespace: voter
data:
    VOTER_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:v/2lSw9xo2x+FD4nNIdo3gXQVnGrMHhd7PkUBB53EiXWzLzbHOAgmMBjqDRk3athbBFO7hoQLWrTH+lN,iv:GyOb/oxobDUM6DNl9YWXgx3cuIAMEUN2jY2uFeyE/MM=,tag:R+pbRPvCHyr7uhRhBjktYg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VW9Cc3VDMkhYWWxpQi85
            cEV1cUJkUzQ4ODNNZGVVcVBUU0p5cENHSVd3CnVaeGxzMEVFY01SdlhCZEN0L2RG
            SFRiemlVVXZ3cDNUcjlWSkNOTHlXM2sKLS0tIDdHUitsS1duanZnbFJrK01GWERN
            NFVPWkJraFRPeHNDNVVYRjFiMExkdW8KdJZ5B3dYoNc5vIuWv2EeUbya7RfE3x+5
            4i9olBJJykR7tOrm5ztRaZtIWzc9IYMiZ+fV6At0FZZxcOrqE48V9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T13:25:56Z"
    mac: ENC[AES256_GCM,data:/G8Orl4ajCz6xRct8mNernWawpebU599VzKdMfYT8qJDisY7Bylz7y/xtapNZa44aFGJkvpUB116mOUTiybCO080YjGALp2FlS6pW7ZabiRHFkv/6qS8RCkEeSIx8SxKqyeUcWfg8DycyY8jbD5pJ2LO3Uybl3chzlEmdnk1Otc=,iv:/QomGqlhzwtKz+nOTAJo45X7Y0tOIlG9h78pQp7D+dI=,tag:heL+t0FiQtGgITXs2Jm86g==,type:str]
    version: 3.13.3
