apiVersion: v1
kind: Secret
metadata:
    name: voter-app-cookie
    namespace: voter
data:
    block-key: ENC[AES256_GCM,data:QikI8EfJL4lk4Sv0Rr+hgq3wHdVyT481GNMMceh5Vhiec4VfldqYN03hYBqSoed7BJIRbitAABUzu/W5,iv:K2nAPP3GoA83kYAwSD7doLmZICnp/98bHhn3/ZlkYI8=,tag:dX0FHlfg0OtMz5d+SbJhyA==,type:str]
    hash-key: ENC[AES256_GCM,data:WUOPk/K7aZoAxto8IObXXSjuDW/DrorcBMGfYxNqeEupRr78BF588lbu+zFpgBA9iwnhTcYr+VFOWjxO,iv:g8kRdz4TmtVKLaMolKjmIGelgtf7Pb/w98ot6ARoQ2g=,tag:p9jPGM80UEyqemSVww/YGQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NUdVK1pRdmg2a0Z4MWtI
            cGpCYVY2c0ZBeDhiVHhTcG9sMjdsN05XMWpBCnFZT2hCUjFQQ0tJdzcyWUdEbFg0
            MzZ5bUFWM09IWDZJamYvUUlBWEZFK0kKLS0tIHpxNVZkeVRFRkNmZlgxTWtFOVlu
            d1V5azZSWVpUeEwwM2ZMNFNTT3RnTmcKakzrpDqcCKpEVWByBTHCFnKXZ+wDG7ni
            HXTUnElaG+PpTlKcAZ84+hApzaHj0fVoPxgGmTGYyD1DRnxK72PiYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T02:45:02Z"
    mac: ENC[AES256_GCM,data:kOgw90zjINvjw1pZ7duTD1ax8WVDxpIcYZBPwdCcOP/qydo8kqZtkOTjp8hz6WT6GXTnO2osGClVzz9F5Td6IchHbmVeQawi123p0Xq1hk13FIR5oEmy7/c7wwV3V8kXEoZGPT+XyqZqBGz2ZcGNj1sx8LS0W2fvYkzbF10DAYI=,iv:wFq6Av50neeckQXPKv9ULKtOadr1BWSzkDDKDrx4qHY=,tag:vxKKw1P3SMpJPFFpay/1nw==,type:str]
    version: 3.13.3
