apiVersion: v1
kind: Secret
metadata:
    name: voter-app-cookie
    namespace: voter
data:
    block-key: ENC[AES256_GCM,data:U7sVJWhQoRpmgjP1TbFUNBXdZsNNwXe9VNTWKzEcCuk1y5s+ifE5QhBY47pjZR8qiSJl4JVDtKcpk0yg,iv:o9OZwgOrn9Vtz4m2w7KLUwfwd3gakc/Q32q3Ov9KUdI=,tag:klmgTzaDyBaTEnQSo3LLVQ==,type:str]
    hash-key: ENC[AES256_GCM,data:wWUuKQ7aiEHq6/p4WmiyqNfIMpgeDDYqsOeChvEd+TiPbIJMocwopPHtnxpbvLApW7ozG1YYEthZg2AJ,iv:KYt+cJqo37824uwErOJI18cm99NMbiJZIIoIry+0zb4=,tag:DJsOvVNRPW2yldxWan+eJw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMXVJTjBJNmEzQkQzeFJY
            d2FncVJIVFNuVVpoeDhheGs2bEVXN2JvQ0hBCm5IYjY4R01OK1pGQ0ZnaGxpMFBX
            UkNna1VYQ3VqNkc2N2FQSVZJeFNqdFkKLS0tIHVmRTFSZ1h0Z29ZYnpvYmpUNGFC
            UFh5M1F4ME1jVG54TUc2TjhEbi9uV2cKjRydQNPQe7sNswqXM6SN9vNcjv9YZwIX
            IeG/+9T7Iut5GiOMod2T/ZNaEsZyqOWHeIKMif4W9yDCLFNS/YuaaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T21:42:20Z"
    mac: ENC[AES256_GCM,data:BMyPJWkH69qAipYBww3ckLEC+W0TnmmqpGyyWLIRQiIY7NO/ouBccpfCZiotiiA+eTWEIejUn15HlezbHWAkNNtbXLwtd+jwucGiPbjLFA+STqiadCy3gY20ZA2E8aMMLvOCprckZpTOJHnQDaPxM7lAzeemps0eE9lK1Y6RzjE=,iv:qMSTIQn9IPZxfGBz82jIiWD2hEqbc/C7tG07YOqohUQ=,tag:5gJXSEm/C088G5koqJK63A==,type:str]
    version: 3.13.3
