apiVersion: v1
kind: Secret
metadata:
    name: voter-oidc-client
    namespace: voter
data:
    VOTER_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:c+7i27z/jSZptcGY1mGY8sdh07QN7WrDZ1RJ7YQAsYy07g+znpvJ2b+4jau8Wk1bEXx2HhxYKtPqLkb0,iv:3PylS3RfMDr1hkxaTIdnTAxy1NJc43eLN4jMO1FOpL0=,tag:Yz+R2P8vXITEDVLDenMhbA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSL1VjeUN5dER5ck1RcmFB
            QXlFOVFaM3BqeWVWekx5bWJIY2ZKUStqSEJvCjBKaWxnaVVBazRVM29EWncyOCtm
            Z2thblJpeXZwajU1d0pwRTVicHAxUGcKLS0tIHlETXJsUFNNajM0REJSekNJNzZu
            OHM2aGNvMDJxZWliSStQWWhOM0djTk0K/NS2ZKQsekddiBueIr0gIrN4zEnz6SXK
            fKBNW46gvJDaMfYqz0/Y2+ec/v4fZhEKUwakPqMRrCa+lhtsNfrXKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T21:42:20Z"
    mac: ENC[AES256_GCM,data:uL/xKd2gnRUbop5ymQKCqF7cXTgwpIcQDFRQEvt+7Fx9L2bIp3fwXGIKsRPIahnDG9M3CMafqdurZsQwwh6vVeZjOTUaHlmKRaxFEjlCp5CgzXDY7fptaafQfvZ1aXp/7okQovZ3/fFoZ+NDaFKpzYIgq99kCxbEQ8F07M9NaDQ=,iv:aIWBnndy/5BB1NKn/1KWAzDTgsvGkGp7CNSsV8BuM58=,tag:uQqySFU80FpH/vky7Ka2RQ==,type:str]
    version: 3.13.3
