apiVersion: v1
kind: Secret
metadata:
    name: voter-app-cookie
    namespace: voter
data:
    block-key: ENC[AES256_GCM,data:StLhmtw29fXwHbE2myMg2hS1hSJyPSEOxqdFsUhUN6edOf1RWlH9NOKtkSCUQovSbCN8Cv5MdR1ZOYRC,iv:JValldb9JfwNSGJqztLXyhzkLReszBvP96n8njtB41w=,tag:4NpBCm6QspatS3kkYitYFA==,type:str]
    hash-key: ENC[AES256_GCM,data:bpg6/PE7l380uyHVaGQBxxKbxI+UGcG2EEbVGvRrHaJIE33ky1Cb8cHi0FzknxplkXYoeaUiHEM+ej6E,iv:5vNVcRUNjMPuGCIarV5SqebZ3EzRcP1U5MoglI1ZNQI=,tag:ZAoiwsOLx6k29T0WLBfeZA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MW9MUTFGcldTbTZicDhw
            ZUhzbXdnRk1tNURncVdzQlpqS3hqYzdvR2tzCnhjRXc4Sk9FYzhIOEJtUjdVd2lk
            dUhvVXpSZWtNazVSZXY1eUs3eHFvUmMKLS0tIDZDSXBuQlZ0aHRVQ0pqTW9ZRXh0
            bUFGVTFFY3VxUklJV0lqbHNVdVhuKzQKzZrM8/9uED1fXow8r4aqYU1oD3bxP1h7
            5QTFSUmInnxA0M7xS4A67ZXhpcgxdwyjmyeSkxFIEchyRNbJmI59FA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T07:58:12Z"
    mac: ENC[AES256_GCM,data:FGTqOv/m1vloEn1NGL0F38sdXFMn7U4yQxtfFTc7U8ocOTrL/FqFDtd5cyE9QQhAOa9uluZ1Bj9HIvayC5fsKFt8iAsNn3MN5Xrt6/6B9Ogy6AiA4RypAdFUToqKfwAMLq9h7bXkVblCPs0ObpISP4QH6EcTVdpKHmWCJMbB290=,iv:ILlIQYz+/N8Cp2LZSUiqEiu8YzeVh87+iGweIBqwvTc=,tag:ZKPRyQmUbaDwQE3ix6bkqQ==,type:str]
    version: 3.13.3
